### ISSUE TITLE
Linux: After 'docker-compose up', /static becomes unavaliable to user due to permissions

### ISSUE THREAD

**Issue by emeraldgreenlight** [Daerdemandt/basic-node#1]
Due to docker operating under root, creating and populating /static is apparently made with root rights. Developer does not seem to be able to create, modify or operate /static in any manner.

**Comment by Daerdemandt** [comment]
As a workaround, creating the folder manually before running `docker-compose up` will suffice.

**Comment by emeraldgreenlight** [comment]
I will test and report if it works. If it does, maybe you should add /static to the repo root, that may fix the issue.

UPD: your proposed workaround works well.

**Comment by emeraldgreenlight** [comment]
Added /static as existing directory. This eliminates the issue.
